# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_IN_AUTOMATION: 'true'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Your-Azure-Service-Connection-Name'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install Terraform
      curl -L /releases.hashicorp.com/terraform/1.7.2/terraform_1.7.2_linux_amd64.zip > terraform.zip
      unzip terraform.zip
      sudo mv terraform /usr/local/bin/
      terraform version

      # Login to Azure
      az account set --subscription $AZURE_SUBSCRIPTION_ID

      # Initialize Terraform
      terraform init

      # Validate Terraform configuration
      terraform validate

      # Apply Terraform configuration
      terraform apply -auto-approve
  env:
    ARM_CLIENT_ID: $(servicePrincipalId)
    ARM_CLIENT_SECRET: $(servicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(subscriptionId)
    ARM_TENANT_ID: $(tenantId)
    ARM_USE_MSI: 'false'
    ARM_SKIP_PROVIDER_REGISTRATION: 'true'
